version : '3.7'
services :
  # postgres 
  db  :
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : postgres
      POSTGRES_PORT : 5432
      POSTGRES_DB : smash_report
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    image : postgres:13.1
    networks :
      back :
        ipv4_address : 192.168.40.10
    ports :
      - 5432:5432
    restart: always
    tty : true
    volumes :
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d
  # node
  api  :
    build :
      context : .
      dockerfile : ./docker/Dockerfile.api
    networks :
      front :
        ipv4_address : 192.168.30.11
      back :
        ipv4_address : 192.168.40.11
    ports :
      - 3000:3000
    restart: always
    tty : true
    volumes :
      - ./server:/app
      - /app/node_modules
      - /app/dist
  # nginx
  web :
    build :
      context : .
      dockerfile : ./docker/Dockerfile.web 
    networks :
      front :
        ipv4_address : 192.168.30.12
    ports :
      - 80:80
    tty : true
    user : root
    volumes :
      - ./client/dist/client:/usr/share/nginx/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf

networks :
  front :
    driver : bridge
    ipam :
      driver : default
      config :
        - subnet : 192.168.30.0/24
          gatway : 192.168.30.1
  back :
    driver : bridge
    ipam :
      driver : default
      config :
        - subnet : 192.168.40.0/24
          gatway : 192.168.40.1
